# Times Series Prediction Using RNN

### What is Recurrent Neural Network?
- A recurrent neural network (RNN) is a type of artificial neural network which uses sequential data or time series data. 

- They are distinguished by their <b>“memory”</b> as they take information from prior inputs to influence the current input and output.

### Types of Recurrent Neural Network Architecture

- Bidirectional recurrent neural networks (BRNN)

- Long short-term memory (LSTM)

- Gated recurrent units (GRUs)

### Objectives

- Build a simple LSTM RNN Model For Time Series Forecasting
- Analyze predictions from the model

---

### Univariate

Univariate time series models are a class of specifications where one attempts to model and to predict financial variables using only information contained in their own past values and possibly current and past values of an error term.

[Link to read more on Univariate](https://www.cambridge.org/core/books/abs/introductory-econometrics-for-finance/univariate-time-series-modelling-and-forecasting/F20C6744BB368689ED4B6C5333BA773F)

## Structure of Univariate dataset modeling




In [1]:
# Years        1    2    3    4    5    6    7    8     9    10   11    12    13
series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]

# Input             Output
#   x1, x2, x3
# 100, 200, 320        400
# 200, 320, 400        530
# 320, 400, 530        370
# 400, 530, 370        600
# 530, 370, 600        710
# 370, 600, 710        890
# 600, 710, 890        ?10
# 710, 890, ?          ??11

## Data pre-processing

In [2]:
import numpy as np

def preprocess_data(series_data, n_features):
    X, y = [], []
    for i in range(len(series_data)):
        input_series_end = i + n_features
        if input_series_end > len(series_data)-1:
            break
        seq_x, seq_y = series_data[i:input_series_end], series_data[input_series_end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [3]:
series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]
n_features = 3
preprocess_data(series_data, n_features)

(array([[100, 200, 320],
        [200, 320, 400],
        [320, 400, 530],
        [400, 530, 370],
        [530, 370, 600],
        [370, 600, 710]]),
 array([400, 530, 370, 600, 710, 890]))

In [4]:
X, y = preprocess_data(series_data, n_features)

In [5]:
X

array([[100, 200, 320],
       [200, 320, 400],
       [320, 400, 530],
       [400, 530, 370],
       [530, 370, 600],
       [370, 600, 710]])

In [6]:
y

array([400, 530, 370, 600, 710, 890])

In [7]:
# Data pre-process function


In [8]:
# series_data

# num_features


In [9]:
# View X
X.shape
# (3, 1)
# (3, 1)
# (6, 3)

(6, 3)

In [10]:
# View y
y

array([400, 530, 370, 600, 710, 890])

In [11]:
# Check shape of X


In [12]:
# Reshape X 
X.shape

(6, 3)

In [13]:
X

array([[100, 200, 320],
       [200, 320, 400],
       [320, 400, 530],
       [400, 530, 370],
       [530, 370, 600],
       [370, 600, 710]])

In [14]:
X = X.reshape(X.shape[0], X.shape[1], 1) #(6, 3) -> (3, 6)

In [15]:
X.ndim

3

In [16]:
X

array([[[100],
        [200],
        [320]],

       [[200],
        [320],
        [400]],

       [[320],
        [400],
        [530]],

       [[400],
        [530],
        [370]],

       [[530],
        [370],
        [600]],

       [[370],
        [600],
        [710]]])

In [17]:
# View X
input_shape = X.shape[1:]

In [18]:
input_shape

(3, 1)

In [19]:
# Import RNN libraries - Models -> Sequential, Layers -> Dense, LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [20]:
# Build RNN Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=input_shape, return_sequences=True))
model.add(LSTM(40, activation='relu'))
model.add(Dense(1))

In [21]:
# Check RNN Model Summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 3, 50)             10400     
                                                                 
 lstm_1 (LSTM)               (None, 40)                14560     
                                                                 
 dense (Dense)               (None, 1)                 41        
                                                                 
Total params: 25,001
Trainable params: 25,001
Non-trainable params: 0
_________________________________________________________________


In [22]:
# Check RNN Model initial_weights
model.get_weights()

[array([[ 0.10707378,  0.05539154,  0.04262863, -0.17168917,  0.13499138,
         -0.12337393,  0.13123474, -0.00243534,  0.13991472, -0.14745471,
          0.00709157, -0.15403001,  0.01499377, -0.06132733, -0.13945174,
         -0.06056024, -0.01429543, -0.09363894,  0.09594369,  0.09517333,
          0.01302175, -0.05152678,  0.16424677,  0.14315161, -0.14611965,
          0.03973749,  0.0350208 ,  0.17013219, -0.03912027, -0.03240182,
         -0.16120371, -0.04131307, -0.10895672,  0.11379656, -0.1610139 ,
          0.01499961, -0.05640323,  0.05802892,  0.06411219,  0.10760084,
         -0.13142425, -0.00048858, -0.11130412,  0.08620647,  0.01843679,
         -0.07616564,  0.12804252, -0.0227941 ,  0.15654051, -0.01395637,
         -0.10760619,  0.02008285,  0.14166543, -0.14939487, -0.01096581,
          0.12611371,  0.00187285, -0.12779622, -0.12902059,  0.01065208,
         -0.13087635,  0.17212549,  0.12926283, -0.02157839,  0.08407089,
         -0.00755708, -0.16144073,  0.

In [23]:
# Compile model
model.compile(optimizer='adam', loss='mse')

In [24]:
# Fit model
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 6s 6s/step - loss: 376794.1250
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 367669.0312
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 361185.8750
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 356381.2188
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 352571.8438
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 348807.2188
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 344129.3438
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 338283.9062
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 332679.3438
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 327940.1250
Epoch 11/100
1/1 [==============================] - 0s 13ms/step - loss: 322623.7188
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 316

1/1 [==============================] - 0s 10ms/step - loss: 8635.2646
Epoch 99/100
1/1 [==============================] - 0s 11ms/step - loss: 8571.1602
Epoch 100/100
1/1 [==============================] - 0s 12ms/step - loss: 8300.1396


In [25]:
# Save model
model.save('savedModel.h5')

In [26]:
# Make predictions
#series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]

In [27]:
model.predict([[370, 600, 710]])

1/1 [==============================] - 1s 953ms/step


array([[790.741]], dtype=float32)

![image](DataImage.jpeg)

## Assignment
#### Model development assignment using Energy(MWh)
#### Reading assignment
- Correlation vs Causation </br>
[Article-1](https://www.lifehack.org/624604/the-most-common-bias-people-have-that-leads-to-wrong-decisions)

In [28]:
import pandas as pd

In [29]:
dataset = pd.read_csv('PowerData.csv')

In [30]:
dataset

Year  Power(MW)
0   1978        174
1   1979        178
2   1980        180
3   1981        200
4   1982        199
5   1983        201
6   1984        186
7   1985        205
8   1986        231
9   1987        238
10  1988        247
11  1989        262
12  1990        274
13  1991        319
14  1992        347
15  1993        415
16  1994        460
17  1995        538
18  1996        562
19  1997        597
20  1998        657
21  1999        658
22  2000        695
23  2001        751
24  2002        712
25  2003        765
26  2004        800
27  2005        842
28  2006        854
29  2007        841
30  2008        927
31  2009        959
32  2010       1115
33  2011       1152
34  2012       1258
35  2013       1432

In [31]:
dataset = dataset.drop(columns=['Year'])

In [32]:
dataset

Power(MW)
0         174
1         178
2         180
3         200
4         199
5         201
6         186
7         205
8         231
9         238
10        247
11        262
12        274
13        319
14        347
15        415
16        460
17        538
18        562
19        597
20        657
21        658
22        695
23        751
24        712
25        765
26        800
27        842
28        854
29        841
30        927
31        959
32       1115
33       1152
34       1258
35       1432

In [33]:
new_series = dataset.iloc[:].values

In [34]:
new_series

array([[ 174],
       [ 178],
       [ 180],
       [ 200],
       [ 199],
       [ 201],
       [ 186],
       [ 205],
       [ 231],
       [ 238],
       [ 247],
       [ 262],
       [ 274],
       [ 319],
       [ 347],
       [ 415],
       [ 460],
       [ 538],
       [ 562],
       [ 597],
       [ 657],
       [ 658],
       [ 695],
       [ 751],
       [ 712],
       [ 765],
       [ 800],
       [ 842],
       [ 854],
       [ 841],
       [ 927],
       [ 959],
       [1115],
       [1152],
       [1258],
       [1432]], dtype=int64)

In [35]:
new_n_features = 3
X, y = preprocess_data(new_series, new_n_features)

In [36]:
X.shape

(33, 3, 1)

In [37]:
new_input_shape = X.shape[1:]

In [38]:
new_input_shape

(3, 1)

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=new_input_shape, return_sequences=True))
model.add(LSTM(100, activation='relu'))
model.add(Dense(1))

In [40]:
model.compile(optimizer='adam', loss='mse')

In [41]:
model.fit(X, y, epochs=200)

Epoch 1/200
2/2 [==============================] - 6s 12ms/step - loss: 484791.6562
Epoch 2/200
2/2 [==============================] - 0s 17ms/step - loss: 465673.8125
Epoch 3/200
2/2 [==============================] - 0s 12ms/step - loss: 453417.8750
Epoch 4/200
2/2 [==============================] - 0s 10ms/step - loss: 442830.2500
Epoch 5/200
2/2 [==============================] - 0s 9ms/step - loss: 431065.2500
Epoch 6/200
2/2 [==============================] - 0s 13ms/step - loss: 417578.3438
Epoch 7/200
2/2 [==============================] - 0s 12ms/step - loss: 401930.5312
Epoch 8/200
2/2 [==============================] - 0s 10ms/step - loss: 377324.7812
Epoch 9/200
2/2 [==============================] - 0s 9ms/step - loss: 341958.7500
Epoch 10/200
2/2 [==============================] - 0s 8ms/step - loss: 295067.5312
Epoch 11/200
2/2 [==============================] - 0s 9ms/step - loss: 245796.7188
Epoch 12/200
2/2 [==============================] - 0s 10ms/step - loss: 17353

2/2 [==============================] - 0s 10ms/step - loss: 4576.1548
Epoch 101/200
2/2 [==============================] - 0s 9ms/step - loss: 4056.3159
Epoch 102/200
2/2 [==============================] - 0s 9ms/step - loss: 3146.8152
Epoch 103/200
2/2 [==============================] - 0s 9ms/step - loss: 2543.4536
Epoch 104/200
2/2 [==============================] - 0s 8ms/step - loss: 2410.3442
Epoch 105/200
2/2 [==============================] - 0s 8ms/step - loss: 2574.5466
Epoch 106/200
2/2 [==============================] - 0s 8ms/step - loss: 2699.4521
Epoch 107/200
2/2 [==============================] - 0s 9ms/step - loss: 2740.3862
Epoch 108/200
2/2 [==============================] - 0s 9ms/step - loss: 2764.0173
Epoch 109/200
2/2 [==============================] - 0s 9ms/step - loss: 2613.2097
Epoch 110/200
2/2 [==============================] - 0s 10ms/step - loss: 2410.1580
Epoch 111/200
2/2 [==============================] - 0s 8ms/step - loss: 2269.7468
Epoch 112/200
2/

2/2 [==============================] - 0s 10ms/step - loss: 3308.3867
Epoch 199/200
2/2 [==============================] - 0s 9ms/step - loss: 2533.6267
Epoch 200/200
2/2 [==============================] - 0s 9ms/step - loss: 2999.3638


In [42]:
model.save('savedPowerModel.h5')

In [43]:
model.predict([[174, 178, 180]])

1/1 [==============================] - 1s 682ms/step


array([[189.59456]], dtype=float32)

In [44]:
dataset

Power(MW)
0         174
1         178
2         180
3         200
4         199
5         201
6         186
7         205
8         231
9         238
10        247
11        262
12        274
13        319
14        347
15        415
16        460
17        538
18        562
19        597
20        657
21        658
22        695
23        751
24        712
25        765
26        800
27        842
28        854
29        841
30        927
31        959
32       1115
33       1152
34       1258
35       1432

In [45]:
model.predict([[1152, 1258, 1432]]) # 1523

1/1 [==============================] - 0s 71ms/step


array([[1340.5853]], dtype=float32)