# Times Series Prediction Using RNN

### What is Recurrent Neural Network?
- A recurrent neural network (RNN) is a type of artificial neural network which uses sequential data or time series data. 

- They are distinguished by their <b>“memory”</b> as they take information from prior inputs to influence the current input and output.

### Types of Recurrent Neural Network Architecture

- Bidirectional recurrent neural networks (BRNN)

- Long short-term memory (LSTM)

- Gated recurrent units (GRUs)

### Objectives

- Build a simple LSTM RNN Model For Time Series Forecasting
- Analyze predictions from the model

---

### Univariate

Univariate time series models are a class of specifications where one attempts to model and to predict financial variables using only information contained in their own past values and possibly current and past values of an error term.

[Link to read more on Univariate](https://www.cambridge.org/core/books/abs/introductory-econometrics-for-finance/univariate-time-series-modelling-and-forecasting/F20C6744BB368689ED4B6C5333BA773F)

## Structure of Univariate dataset modeling




In [2]:
# Years        1    2    3    4    5    6    7    8     9    10   11    12    13
series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]

# Input             Output
#   x1, x2, x3
# 100, 200, 320        400
# 200, 320, 400        530
# 320, 400, 530        370
# 400, 530, 370        600
# 530, 370, 600        710
# 370, 600, 710        890
# 600, 710, 890        ?10
# 710, 890, ?          ??11

## Data pre-processing

In [9]:
import numpy as np

def preprocess_data(series_data, n_features):
    X, y = [], []
    for i in range(len(series_data)):
        input_series_end = i + n_features
        if input_series_end > len(series_data)-1:
            break
        seq_x, seq_y = series_data[i:input_series_end], series_data[input_series_end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [10]:
series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]
n_features = 3
preprocess_data(series_data, n_features)

(array([[100, 200, 320],
        [200, 320, 400],
        [320, 400, 530],
        [400, 530, 370],
        [530, 370, 600],
        [370, 600, 710]]),
 array([400, 530, 370, 600, 710, 890]))

In [11]:
X, y = preprocess_data(series_data, n_features)

In [12]:
X

array([[100, 200, 320],
       [200, 320, 400],
       [320, 400, 530],
       [400, 530, 370],
       [530, 370, 600],
       [370, 600, 710]])

In [13]:
y

array([400, 530, 370, 600, 710, 890])

In [61]:
# Data pre-process function


In [62]:
# series_data

# num_features


In [15]:
# View X
X.shape
# (3, 1)
# (3, 1)
# (6, 3)

(6, 3)

In [18]:
# View y
y

array([400, 530, 370, 600, 710, 890])

In [65]:
# Check shape of X


In [19]:
# Reshape X 
X.shape

(6, 3)

In [20]:
X

array([[100, 200, 320],
       [200, 320, 400],
       [320, 400, 530],
       [400, 530, 370],
       [530, 370, 600],
       [370, 600, 710]])

In [31]:
X = X.reshape(X.shape[0], X.shape[1], 1) #(6, 3) -> (3, 6)

In [33]:
X.ndim

3

In [34]:
X

array([[[100],
        [200],
        [320]],

       [[200],
        [320],
        [400]],

       [[320],
        [400],
        [530]],

       [[400],
        [530],
        [370]],

       [[530],
        [370],
        [600]],

       [[370],
        [600],
        [710]]])

In [38]:
# View X
input_shape = X.shape[1:]

In [39]:
input_shape

(3, 1)

In [36]:
# Import RNN libraries - Models -> Sequential, Layers -> Dense, LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [41]:
# Build RNN Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=input_shape, return_sequences=True))
model.add(LSTM(40, activation='relu'))
model.add(Dense(1))

In [42]:
# Check RNN Model Summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 3, 50)             10400     
                                                                 
 lstm_1 (LSTM)               (None, 40)                14560     
                                                                 
 dense (Dense)               (None, 1)                 41        
                                                                 
Total params: 25,001
Trainable params: 25,001
Non-trainable params: 0
_________________________________________________________________


In [44]:
# Check RNN Model initial_weights
model.get_weights()

[array([[ 1.21245056e-01, -8.47480819e-02, -6.26784414e-02,
          1.38275206e-01,  1.02483630e-01, -9.95695591e-05,
          1.36185259e-01, -8.77325609e-02,  5.73663116e-02,
          1.21439815e-01,  3.36536616e-02, -1.58475339e-01,
          1.63482785e-01, -2.29731202e-04,  3.62761021e-02,
         -8.55730474e-02,  1.36328220e-01,  7.46456385e-02,
          3.91209722e-02, -2.25075632e-02, -5.05544767e-02,
          9.14050341e-02, -2.35060602e-02,  5.91664016e-03,
          2.46404558e-02, -7.52761662e-02,  4.74527627e-02,
          1.33976400e-01, -2.18358785e-02, -1.50011778e-02,
         -5.43161705e-02, -1.36933610e-01,  1.12141162e-01,
          1.61418021e-02, -9.55972746e-02,  1.54703081e-01,
          8.06459785e-02,  1.67218238e-01,  1.04210436e-01,
          5.31560183e-02, -7.68912435e-02, -4.51785326e-02,
          6.05307966e-02,  6.34457767e-02, -4.07170504e-02,
          9.94924009e-02,  1.32360786e-01,  6.39052391e-02,
         -8.09034705e-02, -1.54914245e-0

In [45]:
# Compile model
model.compile(optimizer='adam', loss='mse')

In [48]:
# Fit model
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 17ms/step - loss: 25.0973
Epoch 2/100
1/1 [==============================] - 0s 24ms/step - loss: 21.9696
Epoch 3/100
1/1 [==============================] - 0s 24ms/step - loss: 20.8838
Epoch 4/100
1/1 [==============================] - 0s 20ms/step - loss: 18.5844
Epoch 5/100
1/1 [==============================] - 0s 17ms/step - loss: 16.7272
Epoch 6/100
1/1 [==============================] - 0s 34ms/step - loss: 16.3596
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 15.0688
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 12.7217
Epoch 9/100
1/1 [==============================] - 0s 21ms/step - loss: 11.3931
Epoch 10/100
1/1 [==============================] - 0s 19ms/step - loss: 10.7021
Epoch 11/100
1/1 [==============================] - 0s 22ms/step - loss: 9.0883
Epoch 12/100
1/1 [==============================] - 0s 21ms/step - loss: 7.4765
Epoch 13/100
1/1 [=====================

In [49]:
# Save model
model.save('savedModel.h5')

In [75]:
# Make predictions
#series_data = [100, 200, 320, 400, 530, 370, 600, 710, 890]

In [54]:
model.predict([[370, 600, 710]])

1/1 [==============================] - 0s 83ms/step


array([[890.02936]], dtype=float32)

![image](DataImage.jpeg)

## Assignment
#### Model development assignment using Energy(MWh)
#### Reading assignment
- Correlation vs Causation </br>
[Article-1](https://www.lifehack.org/624604/the-most-common-bias-people-have-that-leads-to-wrong-decisions)

In [55]:
import pandas as pd

In [56]:
dataset = pd.read_csv('PowerData.csv')

In [57]:
dataset

Year  Power(MW)
0   1978        174
1   1979        178
2   1980        180
3   1981        200
4   1982        199
5   1983        201
6   1984        186
7   1985        205
8   1986        231
9   1987        238
10  1988        247
11  1989        262
12  1990        274
13  1991        319
14  1992        347
15  1993        415
16  1994        460
17  1995        538
18  1996        562
19  1997        597
20  1998        657
21  1999        658
22  2000        695
23  2001        751
24  2002        712
25  2003        765
26  2004        800
27  2005        842
28  2006        854
29  2007        841
30  2008        927
31  2009        959
32  2010       1115
33  2011       1152
34  2012       1258
35  2013       1432

In [58]:
dataset = dataset.drop(columns=['Year'])

In [59]:
dataset

Power(MW)
0         174
1         178
2         180
3         200
4         199
5         201
6         186
7         205
8         231
9         238
10        247
11        262
12        274
13        319
14        347
15        415
16        460
17        538
18        562
19        597
20        657
21        658
22        695
23        751
24        712
25        765
26        800
27        842
28        854
29        841
30        927
31        959
32       1115
33       1152
34       1258
35       1432

In [60]:
new_series = dataset.iloc[:].values

In [61]:
new_series

array([[ 174],
       [ 178],
       [ 180],
       [ 200],
       [ 199],
       [ 201],
       [ 186],
       [ 205],
       [ 231],
       [ 238],
       [ 247],
       [ 262],
       [ 274],
       [ 319],
       [ 347],
       [ 415],
       [ 460],
       [ 538],
       [ 562],
       [ 597],
       [ 657],
       [ 658],
       [ 695],
       [ 751],
       [ 712],
       [ 765],
       [ 800],
       [ 842],
       [ 854],
       [ 841],
       [ 927],
       [ 959],
       [1115],
       [1152],
       [1258],
       [1432]], dtype=int64)

In [62]:
new_n_features = 3
X, y = preprocess_data(new_series, new_n_features)

In [66]:
X.shape

(33, 3, 1)

In [67]:
new_input_shape = X.shape[1:]

In [68]:
new_input_shape

(3, 1)

In [69]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=new_input_shape, return_sequences=True))
model.add(LSTM(100, activation='relu'))
model.add(Dense(1))

In [70]:
model.compile(optimizer='adam', loss='mse')

In [72]:
model.fit(X, y, epochs=200)

Epoch 1/200
2/2 [==============================] - 5s 10ms/step - loss: 476924.1875
Epoch 2/200
2/2 [==============================] - 0s 17ms/step - loss: 426861.3750
Epoch 3/200
2/2 [==============================] - 0s 17ms/step - loss: 378552.2812
Epoch 4/200
2/2 [==============================] - 0s 13ms/step - loss: 351128.3750
Epoch 5/200
2/2 [==============================] - 0s 17ms/step - loss: 326518.7812
Epoch 6/200
2/2 [==============================] - 0s 16ms/step - loss: 301083.0000
Epoch 7/200
2/2 [==============================] - 0s 16ms/step - loss: 265525.3750
Epoch 8/200
2/2 [==============================] - 0s 12ms/step - loss: 191682.4531
Epoch 9/200
2/2 [==============================] - 0s 14ms/step - loss: 146157.0938
Epoch 10/200
2/2 [==============================] - 0s 11ms/step - loss: 101640.7031
Epoch 11/200
2/2 [==============================] - 0s 14ms/step - loss: 57198.3203
Epoch 12/200
2/2 [==============================] - 0s 15ms/step - loss: 16

2/2 [==============================] - 0s 10ms/step - loss: 2642.0549
Epoch 100/200
2/2 [==============================] - 0s 10ms/step - loss: 2211.3989
Epoch 101/200
2/2 [==============================] - 0s 10ms/step - loss: 2281.6338
Epoch 102/200
2/2 [==============================] - 0s 10ms/step - loss: 2265.2073
Epoch 103/200
2/2 [==============================] - 0s 12ms/step - loss: 2218.7227
Epoch 104/200
2/2 [==============================] - 0s 11ms/step - loss: 2288.7510
Epoch 105/200
2/2 [==============================] - 0s 11ms/step - loss: 2270.4507
Epoch 106/200
2/2 [==============================] - 0s 15ms/step - loss: 2172.4253
Epoch 107/200
2/2 [==============================] - 0s 16ms/step - loss: 2024.5116
Epoch 108/200
2/2 [==============================] - 0s 10ms/step - loss: 1672.8560
Epoch 109/200
2/2 [==============================] - 0s 12ms/step - loss: 1816.4421
Epoch 110/200
2/2 [==============================] - 0s 12ms/step - loss: 1946.8929
Epoch 

2/2 [==============================] - 0s 20ms/step - loss: 3272.7068
Epoch 197/200
2/2 [==============================] - 0s 28ms/step - loss: 2728.0518
Epoch 198/200
2/2 [==============================] - 0s 14ms/step - loss: 2520.4531
Epoch 199/200
2/2 [==============================] - 0s 15ms/step - loss: 2535.0132
Epoch 200/200
2/2 [==============================] - 0s 11ms/step - loss: 2673.1504


In [73]:
model.save('savedPowerModel.h5')

In [75]:
model.predict([[174, 178, 180]])

1/1 [==============================] - 1s 765ms/step


array([[207.95914]], dtype=float32)

In [74]:
dataset

Power(MW)
0         174
1         178
2         180
3         200
4         199
5         201
6         186
7         205
8         231
9         238
10        247
11        262
12        274
13        319
14        347
15        415
16        460
17        538
18        562
19        597
20        657
21        658
22        695
23        751
24        712
25        765
26        800
27        842
28        854
29        841
30        927
31        959
32       1115
33       1152
34       1258
35       1432

In [76]:
model.predict([[1152, 1258, 1432]]) # 1523

1/1 [==============================] - 0s 84ms/step


array([[1457.9208]], dtype=float32)